  const styles = {
    custom_container: `w-11/12 hidden sm:block`,
    heading: `text-[27px] text-center md:text-start font-semibold font-Roboto pb-5`,
    section: `w-11/12 mx-auto`,
    productTitle: `text-[25px] font-semibold font-Roboto text-gray-800`,
    productDiscountPrice: `font-bold text-[18px] text-gray-800 font-Roboto`,
    price: `font-medium text-[16px] text-red-500 pl-3 mt-[-4px] line-through`,
    shop_name: `pt-3 text-[15px] text-blue-400 pb-3`,
    active_indicator: `absolute bottom-[-27%] left-0 h-[3px] w-full bg-crimson`,
    button: `w-[150px] bg-black h-[50px] my-3 flex items-center justify-center rounded-xl cursor-pointer`,
    cart_button: `px-5 h-[38px] rounded-[20px] bg-[#f63b60] flex items-center justify-center cursor-pointer`,
    cart_button_text: `text-white text-[16px] font-semibold`,
    input: `w-full border p-1 rounded-md`,
    activeStatus: `w-2.5 h-2.5 rounded-full absolute top-0 right-1 bg-green-500`,
    normalFlex: `flex items-center`,
  };